### ISSUE TITLE
0.1.5.0 table sifter chest can't be opened

### ISSUE THREAD

**Issue by valsnoisytoys** [CyanideX/InfernalSkies#19]
When you place a (one block size) chest under a table sifter it can't be opened, so you can't access the chest without breaking it or the table first (it is collecting the stuff tho). (nether/overworld)

**Comment by CyanideX** [comment]
Confirmed to be working clientside:
![Chest](https://dl.dropboxusercontent.com/u/2609913/ShareX/2015/06/2015-06-26_15-58-35.mp4)

Doesn't work on the server though.

**Comment by CyanideX** [comment]
Reported on the [Subsistence repo](https://github.com/CyanideX/Subsistence/issues/109). If you can, could you report any subsistence related issues on that repo? :grinning:

**Comment by valsnoisytoys** [comment]
Sure. If I think its Subsistence, I'll put it there.
