### ISSUE TITLE
0.1.5.0 Server restart may not be loading gamerule changes properly

### ISSUE THREAD

**Issue by valsnoisytoys** [CyanideX/InfernalSkies#26]
Just giving what info I have, because what occurred today may have been due to my attempting to rerun the 0.1.5.0 patch quest multiple times during the testing CyanideX asked me to do to try track down the rain not filling the  barrels issue. Or it might not be due to that.

When our server restarted, it seemed the gamerule changes weren't taking effect properly.
Despite /gamerule doFireTick reporting false, goreae's tree farm went up in (spreading) flames when blazes paid a house call.  Rerunning the command to turn it off again stopped the fire spread. So despite what the server claimed the setting was, it was acting as if it were still on.

The same thing happened with mobGriefing (which we have turned off till the patch to stop skellies from exploding creepers is in) - creeper explosions were destroying property just fine.

I don't have all the data yet, so I don't know if this situation was a one-off (due to my testing mentioned above), or if it's going to happen again. Thus my giving you the details I do have, in case it happens to someone else. :)

**Comment by CyanideX** [comment]
Fire tick, natural regeneration and mob griefing are turned on with the pack update lore. :stuck_out_tongue_winking_eye:

That is how it should be.

The lore runs the command as op and doesn't have an effect on how the server loads the configurations.

**Comment by valsnoisytoys** [comment]
I see. But there is still the issue that the query reports one value but it's actually set to something else.

**Comment by CyanideX** [comment]
That wouldn't be an issue on our end.

**Comment by valsnoisytoys** [comment]
Also, I thought fire tick was turned off on the 0.1.4.2 map? That's why I thought it was supposed to be off.

**Comment by CyanideX** [comment]
The map always starts with fire tick off but is supposed to be re-enabled with the first lore page (which I forgot to add in). I just added it in the update lore to cover anyone that I may have missed.

**Comment by valsnoisytoys** [comment]
Ah. Well, that explains the source of my confusion then. :P
