### ISSUE TITLE
0.1.5.1 Add rocks as a sifting product from gravel and nether grit

### ISSUE THREAD

**Issue by valsnoisytoys** [CyanideX/InfernalSkies#30]
CyanideX agrees it's a good idea. ;)

**Comment by valsnoisytoys** [comment]
Moved to Subsistence repro. Oops.

**Comment by CyanideX** [comment]
This was in the right spot. :stuck_out_tongue_closed_eyes: I know it's hard to differentiate subsistence and infernal skies issues. Basically, anything that's a config issue with subsistence is a fault on my end and, in turn, a pack issue.
